[project]
name = "todo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "freesimplegui>=5.2.0.post1",
    "streamlit>=1.46.1",
]
